### PR TITLE
OCPBUGS-91: document the domain name limitation

### PR DESCRIPTION
**Pull request by alebedev87**
This PR adds a README chapter to document the limitation on the length of the domain names managed by `ExternalDNS` instances.

### CODE REVIEW

**Comment by brandisher** [comment]
I'm going to do the first pass review but will put a hold until someone from NetEdge can do the final review.
/hold

**Review by brandisher — COMMENTED** [review]
These changes to the documentation look straightforward to me and do a good job explaining the limitations. Nice job on the examples!

@candita from the NetEdge team will take a look next and pending approval will remove the hold.

/lgtm

**Comment by alebedev87** [comment]
@brandisher : thanks a lot for coming back to the PR and tagging it. I had to change the diff again after [the discussion](https://coreos.slack.com/archives/CBWMXQJKD/p1666276789391359?thread_ts=1666215643.456259&cid=CBWMXQJKD) we had with @candita yesterday.

Can you, folks, have another look, please?

**Comment by candita** [comment]
Looks good!
/approve

**Comment by brandisher** [comment]
Latest changes look good to me as well!

/lgtm

**Review by candita — APPROVED** [review]

**Review by candita — APPROVED** [review]

**Pull request merged**
