### PR TITLE
docs: add 1.1 release to map table

### PR DESCRIPTION
**Pull request by alebedev87**

### CODE REVIEW

**Comment by alebedev87** [comment]
/hold
Until `1.1` release is shipped.

**Comment by Miciah** [comment]
Since this PR only updates developer documentation, it doesn't require explicit approval from docs, PX, or QE.  
/label docs-approved
/label px-approved
/label qe-approved

**Comment by alebedev87** [comment]
Infoblox licenses we use are temporary (3 months). The instance has been reset to renew them.

/retest

**Comment by alebedev87** [comment]
Error while installing external-dns-operator:
```yaml
  conditions:
  - lastTransitionTime: "2023-01-16T09:21:10Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  - message: 'failed to populate resolver cache from source community-operators/openshift-marketplace:
      failed to list bundles: rpc error: code = Unavailable desc = connection error:
      desc = "transport: Error while dialing dial tcp 172.30.186.96:50051: connect:
      connection refused"'
    reason: ErrorPreventedResolution
    status: "True"
    type: ResolutionFailed
  lastUpdated: "2023-01-16T09:21:10Z"
```
Community operator's catalog service was not responding. This is unrelated to external-dns-operator as it's installed from a different (test) catalog.

/retest

**Comment by alebedev87** [comment]
Same problem of the community operator catalog:
```
    containerStatuses:
    - image: registry.redhat.io/redhat/community-operator-index:v4.12
      imageID: ""
      lastState: {}
      name: registry-server
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: Back-off pulling image "registry.redhat.io/redhat/community-operator-index:v4.12"
          reason: ImagePullBackOff
```

**Pull request merged**
