### PR TITLE
Clean up kubebuilder scaffolding and add `vendor/`

### PR DESCRIPTION
**Pull request by sgreene570**
This PR is a follow-up to #2 and contains the following commits:

---

**Strip out leader election code and yaml** 

The initial kubebuilder scaffolding includes code and resources for managing operator leader election, which we probably don't need for the ExternalDNS operator.

**Add vendor directory for go modules** 

`vendor/`:

Run go mod vendor and commit the outputted `vendor` directory.

`.gitignore`:

Remove comments referencing `vendor/`.

**Add tools/tools.go for vendoring controller-gen** 

`tools/tools.go`:

Add `controller-gen` to a phony `tools` package so that `controller-gen` source is baked into `vendor/`.

`go.mod`/`go.sum`:

Explicitly add `controller-gen` dependency.

`vendor/`:

Vendor controller-gen dependency.

`bin/`:

Stop tracking the controller-gen binary.
 
**Update test Makefile directive** 

`Makefile`:

Add new `CONTROLLER_GEN` variable for running the vendored copy of controller-gen.

Remove `controller-gen` directive as we no longer need to fetch controller-gen during build time.

Modify the `test` directive to call `go test` (prior to this commit, the `test` directive pulled binaries to perform mock e2e tests. We will add e2e tests for real clusters in the near future).

`.gitignore`:

Remove `testbin/` since that directory is no longer used at all.

**Update base CRD controller-gen build version**

### CODE REVIEW

**Comment by Miciah** [comment]
Can we omit the `bin/controller-gen` binary file?

**Comment by sgreene570** [comment]
> Can we omit the `bin/controller-gen` binary file?

interesting, I dont think we can actually since that can't be downloaded during CI runs. Let me amend the .gitignore.

**Comment by Miciah** [comment]
> > Can we omit the `bin/controller-gen` binary file?
> 
> interesting, I dont think we can actually since that can't be downloaded during CI runs. Let me amend the .gitignore.

You should be able to vendor the package (following the example here: https://github.com/openshift/cluster-ingress-operator/blob/master/tools/tools.go#L13) and then build it (or run it using `go run`).  (I'm surprised we _cannot_ download it during CI runs, but we shouldn't _need_ to download it if we package the source and build in CI.)

**Comment by sgreene570** [comment]
> > > Can we omit the `bin/controller-gen` binary file?
> > 
> > 
> > interesting, I dont think we can actually since that can't be downloaded during CI runs. Let me amend the .gitignore.
> 
> You should be able to vendor the package (following the example here: https://github.com/openshift/cluster-ingress-operator/blob/master/tools/tools.go#L13) and then build it (or run it using `go run`). (I'm surprised we _cannot_ download it during CI runs, but we shouldn't _need_ to download it if we package the source and build in CI.)

This was my thinking as well. I'll update this Pr shortly! Thanks.

/hold

**Comment by sgreene570** [comment]
Alright, thanks for the input @Miciah ! This PR should be good to go now, PTAL when you get the chance! :grin: 

/hold cancel

**Comment by sgreene570** [comment]
> I'm surprised we _cannot_ download it during CI runs, but we shouldn't _need_ to download it if we package the source and build in CI.

I believe CI builds happen in a more or less disconnected environment since slorping binaries from the public internet into builds is absolutely a security concern.

**Pull request merged**
